In [2]:
import numpy as np

## DataTypes & Attributes 

In [3]:
#NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2 = np.array([[1,2.0,3.3],
               [4,5,6.5]])

a3 = np.array([[[1,2,3],
              [4,5,6],
               [7,8,9]],
             [[10,11,12],
             [13,14,15],
             [16,17,18]
             ]]
             )

In [6]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [7]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [8]:
a1.shape

(3,)

In [9]:
a2.shape

(2, 3)

In [10]:
a3.shape

(2, 3, 3)

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# Create a Dataframe from a numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating an Array

In [17]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [19]:
sample_array.dtype

dtype('int64')

In [21]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
ones.dtype

dtype('float64')

In [23]:
type(ones)

numpy.ndarray

In [24]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [26]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[7, 1, 2, 7, 5],
       [1, 0, 1, 8, 1],
       [6, 8, 5, 6, 6]])

In [27]:
random_array.size

15

In [28]:
random_array.shape

(3, 5)

In [30]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.37108619, 0.36692588, 0.78198102],
       [0.38950087, 0.4520876 , 0.57251513],
       [0.50994774, 0.50453924, 0.80487116],
       [0.94623836, 0.10893412, 0.82838331],
       [0.01646497, 0.65733727, 0.39618478]])

In [31]:
random_array_2.shape

(5, 3)

In [33]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.43919313, 0.08873588, 0.34460631],
       [0.71335582, 0.05150123, 0.54337349],
       [0.49421941, 0.75925412, 0.04568063],
       [0.1752876 , 0.50714524, 0.62729948],
       [0.45090205, 0.12465941, 0.02550347]])

In [38]:
# Pseudo-random numbers
np.random.seed(seed=0) 
random_array_4 = np.random.randint(10,size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [35]:
random_array_4.shape

(5, 3)

In [43]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## Viewing arrays and matrices 

In [44]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
a1


array([1, 2, 3])

In [47]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [48]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [49]:
a1[0]

np.int64(1)

In [50]:
a2[0]

array([1. , 2. , 3.3])

In [51]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [52]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [54]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[0, 5, 3, 0, 5],
         [7, 1, 8, 4, 9],
         [0, 2, 0, 7, 6],
         [2, 9, 9, 5, 1]],

        [[0, 0, 9, 1, 1],
         [5, 3, 2, 0, 4],
         [8, 7, 1, 4, 9],
         [3, 6, 7, 1, 0]],

        [[2, 7, 0, 0, 9],
         [8, 2, 0, 5, 5],
         [0, 9, 0, 8, 4],
         [5, 1, 4, 0, 7]]],


       [[[2, 0, 3, 9, 8],
         [3, 7, 1, 0, 1],
         [4, 6, 1, 0, 1],
         [0, 1, 8, 4, 1]],

        [[6, 8, 5, 2, 4],
         [7, 4, 1, 2, 8],
         [5, 2, 9, 6, 2],
         [5, 7, 7, 5, 5]],

        [[6, 0, 6, 4, 6],
         [2, 6, 8, 7, 0],
         [5, 8, 9, 7, 7],
         [6, 2, 5, 6, 1]]]])

In [55]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [60]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :4]

array([[[[0, 5, 3, 0],
         [7, 1, 8, 4],
         [0, 2, 0, 7],
         [2, 9, 9, 5]],

        [[0, 0, 9, 1],
         [5, 3, 2, 0],
         [8, 7, 1, 4],
         [3, 6, 7, 1]],

        [[2, 7, 0, 0],
         [8, 2, 0, 5],
         [0, 9, 0, 8],
         [5, 1, 4, 0]]],


       [[[2, 0, 3, 9],
         [3, 7, 1, 0],
         [4, 6, 1, 0],
         [0, 1, 8, 4]],

        [[6, 8, 5, 2],
         [7, 4, 1, 2],
         [5, 2, 9, 6],
         [5, 7, 7, 5]],

        [[6, 0, 6, 4],
         [2, 6, 8, 7],
         [5, 8, 9, 7],
         [6, 2, 5, 6]]]])