In [1]:
import numpy as np

## DataTypes & Attributes 

In [2]:
#NumPy's main datatype is ndarray
a1 = np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1,2.0,3.3],
               [4,5,6.5]])

a3 = np.array([[[1,2,3],
              [4,5,6],
               [7,8,9]],
             [[10,11,12],
             [13,14,15],
             [16,17,18]
             ]]
             )

In [5]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [11]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [13]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
# Create a Dataframe from a numpy array
import pandas as pd

df = pd.DataFrame(a2)
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

## Creating an Array

In [15]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int64')

In [17]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
ones.dtype

dtype('float64')

In [19]:
type(ones)

numpy.ndarray

In [20]:
zeros = np.zeros((2,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [21]:
range_array = np.arange(0,10,2)
range_array

array([0, 2, 4, 6, 8])

In [22]:
random_array = np.random.randint(0,10,size=(3,5))
random_array

array([[1, 8, 6, 5, 0],
       [7, 9, 2, 7, 8],
       [8, 3, 8, 3, 2]])

In [23]:
random_array.size

15

In [24]:
random_array.shape

(3, 5)

In [25]:
random_array_2 = np.random.random((5,3))
random_array_2

array([[0.30285816, 0.69038116, 0.75682968],
       [0.20975497, 0.7421876 , 0.86211119],
       [0.19377706, 0.36592613, 0.8279139 ],
       [0.50543373, 0.32635   , 0.98120598],
       [0.53398005, 0.59235143, 0.87911899]])

In [26]:
random_array_2.shape

(5, 3)

In [27]:
random_array_3 = np.random.rand(5,3)
random_array_3

array([[0.65352678, 0.30822973, 0.97023601],
       [0.69013913, 0.49798964, 0.58479737],
       [0.3250735 , 0.13696337, 0.03199188],
       [0.53738509, 0.56715257, 0.94123947],
       [0.155171  , 0.03682462, 0.82607812]])

In [28]:
# Pseudo-random numbers
np.random.seed(seed=0) 
random_array_4 = np.random.randint(10,size=(5,3))
random_array_4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [29]:
random_array_4.shape

(5, 3)

In [30]:
np.random.seed(7)
random_array_5 = np.random.random((5,3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

## Viewing arrays and matrices 

In [31]:
np.unique(random_array_4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
a1


array([1, 2, 3])

In [33]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [34]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [35]:
a1[0]

np.int64(1)

In [36]:
a2[0]

array([1. , 2. , 3.3])

In [37]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [38]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [39]:
a4 = np.random.randint(10,size=(2,3,4,5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [40]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [41]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :4]

array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])

## Manupulating and comparing Arrays

### Arithmetic

In [42]:
a1

array([1, 2, 3])

In [44]:
ones = np.ones(3)
ones

array([1., 1., 1.])

In [45]:
a1 + ones

array([2., 3., 4.])

In [46]:
a1 - ones

array([0., 1., 2.])

In [47]:
a1 * ones

array([1., 2., 3.])

In [48]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [49]:
a1 * a2 

array([[ 1. ,  4. ,  9.9],
       [ 4. , 10. , 19.5]])

In [50]:
a1 / ones

array([1., 2., 3.])

In [51]:
## floor division removes the decimal (round down)
a2 // a1

array([[1., 1., 1.],
       [4., 2., 2.]])

In [52]:
## power
a2 ** 2

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [53]:
np.square(a2)

array([[ 1.  ,  4.  , 10.89],
       [16.  , 25.  , 42.25]])

In [54]:
np.add(a1,ones)

array([2., 3., 4.])

In [55]:
a1 + ones

array([2., 3., 4.])

In [56]:
a1 % 2

array([1, 0, 1])

In [57]:
np.exp(a1)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [58]:
np.log(a1)

array([0.        , 0.69314718, 1.09861229])

# Aggregation

Aggregation = performing the same operation on a number of things

In [59]:
listy_list = [1,2,3]
type(listy_list)

list

In [60]:
sum(listy_list)

6

In [61]:
massive_array = np.random.random(100000)
massive_array.size

100000

In [62]:
massive_array[:100]

array([0.82845319, 0.94180927, 0.12814785, 0.23043067, 0.6591584 ,
       0.13247399, 0.22407864, 0.57486259, 0.16952372, 0.78223015,
       0.85697563, 0.0336742 , 0.5326448 , 0.79695136, 0.97513968,
       0.27425859, 0.16910106, 0.87670093, 0.90918246, 0.19753289,
       0.44152974, 0.71923214, 0.84534516, 0.16827531, 0.66496896,
       0.80783546, 0.54971412, 0.16471666, 0.0355288 , 0.28153382,
       0.80787085, 0.04476626, 0.00821651, 0.36161665, 0.06362229,
       0.1494863 , 0.02319037, 0.52471984, 0.6966959 , 0.42705349,
       0.13457046, 0.33135721, 0.59034585, 0.94066139, 0.99255772,
       0.24160292, 0.01057991, 0.83064033, 0.92661294, 0.45860348,
       0.77144234, 0.86619903, 0.6096148 , 0.87262718, 0.02390303,
       0.27159522, 0.27721958, 0.12063243, 0.91071345, 0.03043927,
       0.67256103, 0.07133969, 0.36078049, 0.41809954, 0.18140429,
       0.5210141 , 0.53499176, 0.31704388, 0.73708806, 0.16020241,
       0.19250822, 0.35451102, 0.37837613, 0.20628586, 0.91870

In [63]:
%timeit sum(massive_array) ## python sum
%timeit np.sum(massive_array) ## Numpy's sum

7.56 ms ± 46.9 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
22.4 μs ± 35.1 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [64]:
np.mean(a2)

np.float64(3.6333333333333333)

In [65]:
np.max(a2)

np.float64(6.5)

In [66]:
np.min(a2)

np.float64(1.0)

In [67]:
np.std(a2)

np.float64(1.8226964152656422)

In [68]:
np.var(a2)

np.float64(3.3222222222222224)